#!/bin/bash
#PBS -P ob80
#PBS -q normal
#PBS -l ncpus=2
#PBS -l mem=16GB
#PBS -l jobfs=40GB
#PBS -l walltime=60:00
#PBS -l wd
#PBS -l other=hyperthread
#PBS -l storage=scratch/ob80+gdata/ob80
#PBS -N mmseqs_ss


set -euo pipefail
eval "$(conda shell.bash hook)"
conda activate bioinformatics


if [[ ! ${IN:-} ]]; then 
	echo "$0 <input taxonomy _report.gz file>";
	exit 1;
fi

OUT=${IN/_report.gz/_report_subsystems.gz}
if [[ -e $OUT ]]; then echo "Nothing to do for $IN writing to $OUT" 2>&1; exit 0; fi

python ~/GitHubs/atavide_lite/bin/easy_taxonomy_to_function.py -f $IN -d /home/584/re3494/databases/uniref.sqlite | gzip -c >  $OUT
